version: "2"

services:
  web:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "text_geocoder.app:create_app()"
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
